### ISSUE TITLE
Release a stable version

### ISSUE THREAD

**Issue by damiencal** [wnabil/ngx-drupal8-rest#6]
Releasing a a version 1.0.0 will likely help increase use of this module as it seems stable.

Also please update the dependencies:
npm WARN ngx-drupal8-rest@0.0.14-beta requires a peer of @angular/common@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-drupal8-rest@0.0.14-beta requires a peer of @angular/core@^7.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by wnabil** [comment]
v1.12 is a stable version, register account added and tested, docs coming soon
